---

# This Ansible Configuration will install a functioning router that will connect to a nearby wifi and share to LAN ports
# 
# Services provided in install:
# DHCP, DNS(Bind9), NTP, internet sharing, traffic shaping(TC), web interface via cockpit
#

- hosts: 127.0.0.1
  gather_facts: yes
  user: root
  connection: ssh
  become: yes

  vars:
    NETPLANTEMPLATE: 'apu4lanonly.netplan.j2'
    INTERNETNIC: wlp5s0
    LANNIC: LAN0
    SSID: TestWifi
    PSK: Testpassword
    WIFI: wlp5s0
    WANIP: 192.168.0.100
    WANDNS: 192.168.0.1    
    WAN: 192.168.0.0    
    WANGATE: 192.168.0.1
    LANGATE: 10.0.75.2
    LANIP: 10.0.75.2
    LANDNS: 10.0.75.2
    LAN: 10.0.75.0
    LANRANGE: "10.0.75.100 10.0.75.199"
    LANDOMAIN: home.lan
    LANREVDOMAIN: home.lan.rev
    LANREVIP: 75.0.10
    LANNTP: 10.0.75.2
    HOSTNAME: dallaley
    RNDCKEY: 'G0/f1m00twTj4VHW74lZ7R1DiUJR0KgO3/D0Wgk1uyVlcbXsWaQBYy5VYtfcdlTZkOcx5ft75PkEaXUW7VC3gw=='
    ZABBIXPW: Test0001
  tasks:

  roles:
   - wifisetup
   - netplan
   - packagesupgrade
   - ishare
   - ntpserver
   - dhcpserver
   - bind9server
   - baseapps
   - cockpit
#   - zabbixserver
#   - trafficshape
